### ISSUE TITLE
catalog_product_index_eav_tmpx is full

### ISSUE THREAD

**Issue by JustinElst** [smart-devs/smartdevs-indexer#1]
I get this sql error, But the table doesn't even exist.

```
SQLSTATE[HY000]: General error: 1114 The table 'catalog_product_index_eav_tmpx' is full, query was: ****
```

Do you know a quick fix?

**Comment by dng-dev** [comment]
increase max heap table size and max tmp table size
max_heap_table_size = 256M
tmp_table_size = 256M

**Comment by JustinElst** [comment]
Cool, thanks.
I am using a Amazon AWS RDS db.t2.micro for dev at the moment. Which has ~615mb of usable memory (with the base/recommended mysql settings) But i am testing with about 23.000 products.. 
So It sounds like a good idea to upgrade :)
What instance class would you recommend (which inherently would have those settings in place)
db.m1.small     ~1.7gb (usable)
db.m3.medium ~3.75gb (usable)
db.m3.large      ~7.5GB (usable)

**Comment by dng-dev** [comment]
Hi,

i am using local Vagrant for developing. For Production on aws i check the needed Memory for InnoDB + 1G for OS and around 5MB / Connection.

So its hard to find a recommendation. In my opinion i will suggest to use db.m3.medium and configure innodb_buffer_pool to around 1.536MB

**Comment by dng-dev** [comment]
Have you checked that the HDD is not full during indexing?

**Comment by JustinElst** [comment]
Cool, tnx for the tips. It works like a charm now.
Are you using this module in production? Because as i can conclude in my verry limited test it all seems to reindex correctly..
