### ISSUE TITLE
Why are you replacing PDO/Mysql?

### ISSUE THREAD

**Issue by maderlock** [smart-devs/smartdevs-indexer#3]
The module is a really good idea, but I'm nervous about using it without some explanation as to why you are overriding this class. What is the reasoning?

**Comment by dng-dev** [comment]
Have You tried a diff of the files? I am not shure anymore. I think the reason was to implement the possibility to create a tempoary table. I don't have the time now to make a diff of the file. Feel free to post the diff and i will explain it. to you.

**Comment by dng-dev** [comment]
Removed the Rewrite
